
export const AFRICAN_COUNTRIES = [
  { name: 'Algeria', code: 'DZ', currency: 'DZD', symbol: 'د.ج' },
  { name: 'Angola', code: 'AO', currency: 'AOA', symbol: 'Kz' },
  { name: 'Benin', code: 'BJ', currency: 'XOF', symbol: 'CFA' },
  { name: 'Botswana', code: 'BW', currency: 'BWP', symbol: 'P' },
  { name: 'Burkina Faso', code: 'BF', currency: 'XOF', symbol: 'CFA' },
  { name: 'Burundi', code: 'BI', currency: 'BIF', symbol: 'FBu' },
  { name: 'Cabo Verde', code: 'CV', currency: 'CVE', symbol: '$' },
  { name: 'Cameroon', code: 'CM', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Central African Republic', code: 'CF', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Chad', code: 'TD', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Comoros', code: 'KM', currency: 'KMF', symbol: 'CF' },
  { name: 'Congo (Congo-Brazzaville)', code: 'CG', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Congo (DRC)', code: 'CD', currency: 'CDF', symbol: 'FC' },
  { name: 'Djibouti', code: 'DJ', currency: 'DJF', symbol: 'Fdj' },
  { name: 'Egypt', code: 'EG', currency: 'EGP', symbol: 'E£' },
  { name: 'Equatorial Guinea', code: 'GQ', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Eritrea', code: 'ER', currency: 'ERN', symbol: 'Nfk' },
  { name: 'Eswatini', code: 'SZ', currency: 'SZL', symbol: 'L' },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', symbol: 'Br' },
  { name: 'Gabon', code: 'GA', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Gambia', code: 'GM', currency: 'GMD', symbol: 'D' },
  { name: 'Ghana', code: 'GH', currency: 'GHS', symbol: 'GH₵' },
  { name: 'Guinea', code: 'GN', currency: 'GNF', symbol: 'FG' },
  { name: 'Guinea-Bissau', code: 'GW', currency: 'XOF', symbol: 'CFA' },
  { name: 'Ivory Coast', code: 'CI', currency: 'XOF', symbol: 'CFA' },
  { name: 'Kenya', code: 'KE', currency: 'KES', symbol: 'KSh' },
  { name: 'Lesotho', code: 'LS', currency: 'LSL', symbol: 'L' },
  { name: 'Liberia', code: 'LR', currency: 'LRD', symbol: 'L$' },
  { name: 'Libya', code: 'LY', currency: 'LYD', symbol: 'LD' },
  { name: 'Madagascar', code: 'MG', currency: 'MGA', symbol: 'Ar' },
  { name: 'Malawi', code: 'MW', currency: 'MWK', symbol: 'MK' },
  { name: 'Mali', code: 'ML', currency: 'XOF', symbol: 'CFA' },
  { name: 'Mauritania', code: 'MR', currency: 'MRU', symbol: 'UM' },
  { name: 'Mauritius', code: 'MU', currency: 'MUR', symbol: '₨' },
  { name: 'Morocco', code: 'MA', currency: 'MAD', symbol: 'DH' },
  { name: 'Mozambique', code: 'MZ', currency: 'MZN', symbol: 'MT' },
  { name: 'Namibia', code: 'NA', currency: 'NAD', symbol: 'N$' },
  { name: 'Niger', code: 'NE', currency: 'XOF', symbol: 'CFA' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', symbol: '₦' },
  { name: 'Rwanda', code: 'RW', currency: 'RWF', symbol: 'FRw' },
  { name: 'Sao Tome and Principe', code: 'ST', currency: 'STN', symbol: 'Db' },
  { name: 'Senegal', code: 'SN', currency: 'XOF', symbol: 'CFA' },
  { name: 'Seychelles', code: 'SC', currency: 'SCR', symbol: '₨' },
  { name: 'Sierra Leone', code: 'SL', currency: 'SLL', symbol: 'Le' },
  { name: 'Somalia', code: 'SO', currency: 'SOS', symbol: 'Sh.So.' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', symbol: 'R' },
  { name: 'South Sudan', code: 'SS', currency: 'SSP', symbol: '£' },
  { name: 'Sudan', code: 'SD', currency: 'SDG', symbol: 'S£' },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', symbol: 'TSh' },
  { name: 'Togo', code: 'TG', currency: 'XOF', symbol: 'CFA' },
  { name: 'Tunisia', code: 'TN', currency: 'TND', symbol: 'DT' },
  { name: 'Uganda', code: 'UG', currency: 'UGX', symbol: 'USh' },
  { name: 'Zambia', code: 'ZM', currency: 'ZMW', symbol: 'ZK' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', symbol: '$' }
];
